# Generated by Django 6.0.5 on 2026-05-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vest',
            options={'verbose_name_plural': 'Vesti'},
        ),
    ]
