# Generated by Django 6.0.5 on 2026-05-12 17:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('slika', models.ImageField(upload_to='rec/')),
                ('tekst', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
