# Generated by Django 6.0.5 on 2026-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='tekst',
        ),
        migrations.AddField(
            model_name='rec',
            name='citat',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec',
            name='paragraf1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec',
            name='paragraf2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec',
            name='paragraf3',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
