# Generated by Django 6.0.5 on 2026-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rec_tekst_rec_citat_rec_paragraf1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='paragraf1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rec',
            name='paragraf2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rec',
            name='paragraf3',
            field=models.TextField(),
        ),
    ]
