# Generated by Django 5.2.12 on 2026-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_artwork_alter_rec_id_alter_vest_id_alter_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назив филма')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='bioskop/', verbose_name='Постер')),
                ('screening_date', models.DateTimeField(verbose_name='Датум и вријеме пројекције')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена карте')),
                ('tag', models.CharField(blank=True, choices=[('premijera', 'Премијера'), ('klasik', 'Класик'), ('domaci', 'Домаћи филм'), ('strani', 'Страни филм'), ('uskoro', 'Ускоро'), ('poseban', 'Посебна пројекција')], max_length=20, verbose_name='Ознака')),
                ('featured', models.BooleanField(default=False, verbose_name='Истакнути филм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Filmovi',
                'ordering': ['screening_date'],
            },
        ),
    ]
