# Generated by Django 6.0.5 on 2026-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('cena', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
