# Generated by Django 6.0.5 on 2026-05-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cena',
            field=models.IntegerField(),
        ),
    ]
